// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Mw-D0q2uHAUWAzHvv8pcdMh-YFyKZTU',
    appId: '1:353758540384:web:42d1e3376d6ec8e65b8905',
    messagingSenderId: '353758540384',
    projectId: 'tu-recorrido-dev',
    authDomain: 'tu-recorrido-dev.firebaseapp.com',
    storageBucket: 'tu-recorrido-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtDltcgsW58yciMfkVSskO5yWNK-vu8X8',
    appId: '1:353758540384:android:0e10d1bda79accd55b8905',
    messagingSenderId: '353758540384',
    projectId: 'tu-recorrido-dev',
    storageBucket: 'tu-recorrido-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7xTpzUJ4XnvKW-zQV9aUhCy6m09v9ERo',
    appId: '1:353758540384:ios:6cc9fa3e5b469b555b8905',
    messagingSenderId: '353758540384',
    projectId: 'tu-recorrido-dev',
    storageBucket: 'tu-recorrido-dev.firebasestorage.app',
    iosBundleId: 'com.turecorrido.app',
  );
}
